# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'GenCon-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GenCon-iOS
  pod 'ObjectMapper'
  pod 'Alamofire'
  pod 'Koyomi'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'Material'
  pod 'R.swift'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'
end
